<?php

namespace App\Imports;

use App\Models\Student;
use App\Models\StudentGuardian;
use App\Models\SchoolYearStudent;
use App\Models\SchoolYear;
use Illuminate\Support\Collection;
use Illuminate\Support\Facades\DB;
use Maatwebsite\Excel\Concerns\ToCollection;
use Maatwebsite\Excel\Concerns\WithHeadingRow;

class StudentsImport implements ToCollection, WithHeadingRow
{
    public function collection(Collection $rows)
    {
        // 1. Get the latest school year based on your specific sorting requirements
        $latestSchoolYear = SchoolYear::orderByDesc('sy_to')
            ->orderByDesc('school_term_id')
            ->first();

        if (!$latestSchoolYear) {
            throw new \Exception('No School Year found in the database. Please create one first.');
        }

        // 2. Wrap in a database transaction. If one row fails, nothing gets inserted (prevents partial dirty data).
        DB::transaction(function () use ($rows, $latestSchoolYear) {
            foreach ($rows as $row) {
                // Skip empty rows
                if (!isset($row['lrn_no'])) {
                    continue;
                }

                // 3. Create or Update the Student
                // Assuming 'lrn_no' is the unique identifier in your excel file
                $student = Student::updateOrCreate(
                    ['lrn_no' => $row['lrn_no']], 
                    [
                        'lastname'       => $row['lastname'] ?? null,
                        'firstname'      => $row['firstname'] ?? null,
                        'middlename'     => $row['middlename'] ?? null,
                        'extname'        => $row['extname'] ?? null,
                        'contact_no'     => $row['contact_no'] ?? null,
                        'email'          => $row['email'] ?? null,
                        'sex'            => $row['sex'] ?? null,
                        'birthdate'      => isset($row['birthdate']) ? \PhpOffice\PhpSpreadsheet\Shared\Date::excelToDateTimeObject($row['birthdate']) : null,
                        'address'        => $row['address'] ?? null,
                        
                        // Link to the latest school year retrieved above
                        'school_year_id' => $latestSchoolYear->id,
                        'sy_from'        => $latestSchoolYear->sy_from,
                        'sy_to'          => $latestSchoolYear->sy_to,
                        
                        'level'          => $row['level'] ?? null,
                        'grade'          => $row['grade'] ?? null,
                        'section'        => $row['section'] ?? null,
                        'status'         => 'active', // Default status assumption
                        
                        // Note: student_id is automatically generated by your booted() method if it's a new record!
                    ]
                );

                // 4. Create or Update Guardian (if provided in excel)
                if (isset($row['guardian_name'])) {
                    StudentGuardian::updateOrCreate(
                        ['student_id' => $student->id],
                        [
                            'name'       => $row['guardian_name'],
                            'contact_no' => $row['guardian_contact_no'] ?? null,
                            'email'      => $row['guardian_email'] ?? null,
                        ]
                    );
                }

                // 5. Create the SchoolYearStudent pivot/history record
                SchoolYearStudent::updateOrCreate(
                    [
                        'student_id'     => $student->id,
                        'school_year_id' => $latestSchoolYear->id,
                    ],
                    [
                        'sy_from'        => $latestSchoolYear->sy_from,
                        'sy_to'          => $latestSchoolYear->sy_to,
                        'level'          => $row['level'] ?? null,
                        'grade'          => $row['grade'] ?? null,
                        'section'        => $row['section'] ?? null,
                        'status'         => 'enrolled',
                    ]
                );
            }
        });
    }
}